CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Name] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Password] VARCHAR(800) DEFAULT '',
	[RoleId] INT FOREIGN KEY REFERENCES [dbo].[Role](Id)
)
